cars/urls.py
# from django.contrib import admin
# from django.urls import path, include

# urlpatterns = [
#     path('', include('cars.urls')),
#     path('admin/', admin.site.urls),
# ]


from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.CarListView.as_view(), name='all'),
    path('cars/<int:pk>/detail/', views.CarDetailView.as_view(), name='car_detail'),
    path('cars/create/', views.CarCreateView.as_view(), name='car_create'),
    path('cars/<int:pk>/update/', views.CarUpdateView.as_view(), name='car_update'),
    path('cars/<int:pk>/delete/', views.CarDeleteView.as_view(), name='car_delete'),
    path('cars/update/bulk/', views.update_cars_view),
    path('api/colors/', views.get_colors),
    path('api/brands/', views.get_brands),
    path('api/cars/', views.get_cars),
    path('api/cars/update/bulk/', views.update_cars),
]

challenge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cars.urls')),
    path('admin/', admin.site.urls),
]

cars/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.



class Brand(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Car(models.Model):
    COLOR_CHOICES = (
        ('white', 'White'),
        ('red', 'Red'),
        ('blue','Blue'),
        ('black','Black'),
        ('yellow','Yellow'),
        ('gray','Gray'),
    )


    model = models.CharField(max_length=50)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    color = models.CharField(max_length=50, choices=COLOR_CHOICES)
    value = models.IntegerField(validators=[MinValueValidator(0)])
    production_cost = models.IntegerField(validators=[MinValueValidator(0)])
    transportation_cost = models.IntegerField(validators=[MinValueValidator(0)])


    def __str__(self):
        return f"{self.model} {self.id}"

cars/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy
from django.http import JsonResponse
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Car, Brand
from .serializers import CarSerializer, BrandSerializer
import json


class CarBaseView(View):
    model = Car
    fields = '__all__'
    success_url = reverse_lazy('cars:all')


class CarListView(CarBaseView, ListView):
    """View to list all cars
    """

class CarDetailView(CarBaseView, DetailView):
    """View to list the details from one car
    """

class CarCreateView(CarBaseView, CreateView):
    """View to create a new car
    """

class CarUpdateView(CarBaseView, UpdateView):
    """View to update a car
    """

class CarDeleteView(CarBaseView, DeleteView):
    """View to delete a car
    """


def update_cars_view(request):
    return render(request, 'cars/car_panel.html')


@api_view(["GET"])
def get_colors(requets):
    colors = Car.COLOR_CHOICES,
    response = [{"tag": tag, "name": name} for tag, name in colors[0]]
    return JsonResponse({'colors': response}, safe=False, status=status.HTTP_200_OK)
        


@api_view(["GET"])
def get_brands(requets):
    brands = Brand.objects.all()
    serializer = BrandSerializer(brands, many=True)
    return JsonResponse({'brands': serializer.data}, safe=False, status=status.HTTP_200_OK)


@api_view(["GET"])
def get_cars(request):
    cars = Car.objects.all()
    serializer = CarSerializer(cars, many=True)
    return JsonResponse({'cars': serializer.data}, safe=False, status=status.HTTP_200_OK)

@csrf_exempt
@api_view(["PUT"])
def update_cars(request):
    update_serializer = CarSerializer(data=request.data, many=True)

    if update_serializer.is_valid(raise_exception=True):
        for item in update_serializer.validated_data:
            car = Car.objects.get(id=item['id'])
            car.model = item.get("model")
            car.brand = item.get("brand")
            car.color = item.get("color")
            car.value = item.get("value")
            car.production_cost = item.get("production_cost")
            car.transportation_cost = item.get("transportation_cost")
            car.save()

    cars = Car.objects.all()
    serializer = CarSerializer(cars, many=True)
    
    return JsonResponse({'cars':serializer.data}, safe=False, status=status.HTTP_200_OK)

cars/templates/cars/car_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'cars:all' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete Car</h1>

        <p class="h5">Are you sure you want to delete the Car:</p>
        <h3 class="my-5">{{ car.title }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url 'cars:all' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

cars/templates/cars/car_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Car Details</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for label, value in car.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}
                        
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'cars:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

cars/templates/cars/car_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'cars:all' %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

cars/templates/cars/car_list.html
{% extends 'base.html' %}

{% block content %}
{% for car in car_list %}
    {% for colname in car.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">My cars</h1>
        <div class="d-flex justify-content-center">
            <a href="{% url 'cars:car_create' %}" class="d-block btn btn-primary my-3">Add New</a>
        </div>
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Model</th>
                    <th class="text-center" scope="col">Brand</th>
                    <th class="text-center" scope="col">Main Color</th>
                    <th class="text-center" scope="col">Value</th>
                    <th class="text-center" scope="col">Production Cost</th>
                    <th class="text-center" scope="col">Trasportation Cost</th>
                    <th class="text-center" scope="col">Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for car in car_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5"><a href="{% url 'cars:car_detail' car.id %}">{{car.model}}</a></td>
                    <td class="text-center">{{car.brand}}</td>
                    <td class="text-center">{{car.color}}</td>
                    <td class="text-center">{{car.value}}</td>
                    <td class="text-center">{{car.production_cost}}</td>
                    <td class="text-center">{{car.transportation_cost}}</td>
                    <td class="text-center">{{car.production_cost|add:car.transportation_cost}}</td>
                    <td><a href="{% url 'cars:car_update' car.id %} ">Update</a></td>
                    
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        
    </div>
        
</div>

{% endblock content %}

cars/templates/cars/car_panel.html
{% extends 'base.html' %}


{% block content %}

<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">List of cars</h1>
        <div class="d-flex justify-content-center">
            <a href="{% url 'cars:car_create' %}" class="d-block btn btn-primary my-3">Add New</a>
        </div>
        <div class="d-flex justify-content-center">
            <a href="" class="d-block btn btn-primary my-3">Cancel</a>
            <button id="update-button" class="d-block btn btn-primary my-3">Save</button>
        </div>
        <table class="table table-striped mt-5" id="cars">
            <thead>
                <tr>
                    
                    <th class="text-center" scope="col">Model</th>
                    <th class="text-center" scope="col">Brand</th>
                    <th class="text-center" scope="col">Main Color</th>
                    <th class="text-center" scope="col">Value</th>
                    <th class="text-center" scope="col">Production Cost</th>
                    <th class="text-center" scope="col">Trasportation Cost</th>
                    <th class="text-center" scope="col">Total</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>    
        
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script>
    var COLORS;
    var BRANDS;

    var fill_table = () => {
        $.ajax({
            url: '/api/colors/',
            method: 'GET',
            success: function(response) {
                COLORS = response.colors;
                $.ajax({
                    url: '/api/brands/',
                    method: 'GET',
                    success: function(response) {
                        BRANDS = response.brands;
                        $.ajax({
                            url: '/api/cars/',
                            method: 'GET',
                            success: function(response) {
                                var tbody = $('#cars tbody');
                                $.each(response.cars, function(index, item) {
                                    var row = $('<tr>');
                                    row.append($('<td class="car-id" style="display:none">').text(item.id));
                                    row.append($('<td>').append($('<input class="model-input">').val(item.model)));
                                    var brandSelect = $('<select class="brand-select">');
                                    $.each(BRANDS, function(i, brand) {
                                        var option = $('<option>').val(brand.id).text(brand.name);
                                        if (brand.id === item.brand) {
                                            option.attr('selected', true);
                                        }
                                        brandSelect.append(option);
                                    });
                                    row.append($('<td>').append(brandSelect));
                                    var colorSelect = $('<select class="color-select">');
                                    $.each(COLORS, function(i, color) {
                                        var option = $('<option>').val(color.tag).text(color.name);
                                        if (color.tag === item.color) {
                                            option.attr('selected', true);
                                        }
                                        colorSelect.append(option);
                                    });
                                    row.append($('<td>').append(colorSelect));
                                    row.append($('<td>').append($('<input class="value-input">').val(item.value)));
                                    row.append($('<td>').append($('<input class="production-cost-input">').val(item.production_cost)));
                                    row.append($('<td>').append($('<input class="transportation-cost-input">').val(item.transportation_cost)));
                                    row.append($('<td class="total">').text(item.transportation_cost + item.production_cost));
                                    tbody.append(row);
                                });
                            },
                            error: function(error) {
                                console.error(error);
                            }
                        });
                    },
                    error: function(error) {
                        console.error(error);
                    }
                });
            },
            error: function(error) {
                console.error(error);
            }
        });
    };

    var retrieve_data = () => {
        var data = [];
        $('#cars tbody tr').each(function() {
            var row = {};
            var id = parseInt($(this).find('.car-id').text());
            var model = $(this).find('.model-input').val();
            var brand = $(this).find('.brand-select').val();
            var color = $(this).find('.color-select').val();
            var value = parseInt($(this).find('.value-input').val());
            var production_cost = parseInt($(this).find('.production-cost-input').val());
            var transportation_cost = parseInt($(this).find('.transportation-cost-input').val());

            row.id = id;
            row.model = model;
            row.brand = brand;
            row.color = color;
            row.value = value;
            row.production_cost = production_cost;
            row.transportation_cost = transportation_cost;

            data.push(row);
        });

        return data;
    }

    $(document).ready(function() {
        fill_table();

        $('#cars').on('input', '.production-cost-input, .transportation-cost-input', function() {
            var row = $(this).closest('tr');
            var production_cost = parseInt(row.find('.production-cost-input').val());
            var transportation_cost = parseInt(row.find('.transportation-cost-input').val());
            var total = row.find('.total');

            total.text(production_cost+transportation_cost);
        });

        $('#update-button').click(function() {
            var data = retrieve_data();
            console.log(data);
            $.ajax({
                url: '/api/cars/update/bulk/',
                method: 'PUT',
                data: JSON.stringify(data),
                contentType: 'application/json',
                success: function(response) {
                    console.log('PUT request successful');
                },
                error: function(error) {
                    console.log(error);
                }
            });
        });
    });
  </script>
{% endblock scripts %}

templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">


{% block title %}
    {% if title %}
        <title>{{title}} | My Cars</title> 
    {% else %}
        <title>My Cars Table</title>
    {% endif %}
{% endblock title %}

{% block head %}
{% endblock head %}
    
</head>

<body>

<div class="container-fluid">
    
    <!-- NAVIGATION BAR -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="d-flex justify-content-between px-5 mx-auto" style="width: 80%;">
            <span class="navbar-text text-white">DJANGO C.R.U.D.</span>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'cars:all' %}">CARS</a>
                </li>
                
                <!-- 
                ##
                ## UNCOMMENT THESE LINES IF YOU HAVE A FUNCTIONAL CRUD FOR THE GENRE MODEL 
                ## CHANGE ALSO THE URL INFO 'cars:all' to 'cars:genre_all'     
                
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'cars:all' %}">Genres</a>
                </li>

                -->

                <li class="nav-item active">
                </li>
            </ul>
        </div>
    </nav>

    <!-- END OF NAVIGATION BAR -->

</div>

{% block content %}
{% endblock content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

{% block scripts %}
{% endblock scripts %}

</body>

</html>